encryption_key: someRandomBINARYKEY
mailer:
  server: mail.example.com
  username: someLOGIN
  password: s0meth1ngs3cr3t
paypal:
  ip:         192.168.0.1
  login:      someLOGIN.yahoo.com
  password:   somePASSWORD
  signature:  someSIGNATURE
authnet:
  login:      <%= ENV['AUTHNET_LOGIN'] %>
  password:   <%= ENV['AUTHNET_PASSWORD'] %>
vat: false
require_state_in_address: true
force_ssl: false
redirect: false
redirect_www: false

in_signup_period: false
allow_preorders: true
allow_orders: true

want_login_header: false

# tax_per_state_id is a field for tax being applied at the state level or country wide level in "TaxRate model"
tax_per_state_id: true

email_list:
  daily_report: ['drhenner@example.com']

paperclip:
  s3_protocol: https
  s3_credentials:
    access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
    secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  path: ':class/:attachment/:style/:hash.:extension'
  bucket: <%= ENV['FOG_DIRECTORY'] %>
  hash_secret: someSecretHash
google:
  analytics_code: UA-38891059-1
  rore_analytics_code: UA-38891059-1
stripe:
  secret_key: <%= ENV['STRIPE_SECRET_KEY'] %>
  publishable_key: <%= ENV['STRIPE_PUBLISHABLE_KEY'] %>

mandrill:
  host: smtp.mandrillapp.com
  port: 587
  smtp_username: <%= ENV['MANDRILL_USERNAME'] %>
  smtp_password: <%= ENV['MANDRILL_APIKEY'] %>

mailchimp:
  api_key: <%= ENV['MAILCHIMP_API_KEY'] %>